### ISSUE TITLE
Security: unpublished programs are viewable through API by unauthenticated users

### ISSUE THREAD

**Issue by j-selby** [j-selby/CASS-Degrees-Code#282]
There exists an issue where unauthenticated users can access components of the database that they otherwise shouldn't be able to.

For example, the request '/api/search/?from=program&publish=false' will return all programs (another bug with `publish` not being respected?), including staff notes and unpublished courses, regardless of the user's login status.

As this could be assumed to be private, some level of security/query sanity should be applied to this endpoint.

**Comment by JackSekoranja** [comment]
`/api/search/?from=program&publish=false` returns all programs because you need to specify you are retrieving `publish` for it to work (which was done for simplicities sake). E.g. `/api/search/?select=name,code,publish&from=program&publish=false` would work.

It's currently public as we haven't found a good way to allow live javascript updates (both when authenticated or otherwise) except through this method. As a result this may be quite difficult to improve

**Comment by j-selby** [comment]
Implemented by #362 a couple of days ago.
