### ISSUE TITLE
Cancel Button in Create Course/Subplan/Program Links to Staff Home Page

### ISSUE THREAD

**Issue by spencerj411** [j-selby/CASS-Degrees-Code#342]
When you Edit a Course/Subplan/Program, and click the Cancel button at the bottom, it links you back to the _Program, Subplan, and Course List_ page. However, when you **Create or Duplicate** a Course/Subplan/Program, clicking the Cancel button will link you back to the staff homepage. If this is intentional, please delete this issue.

**Comment by KavsHub** [comment]
I feel like for consistency we should link back to where they came from previously.

However, I think the reason why they go back to the homepage is because the create program/subplan/course main page's cancel button's redirect to home if you press cancel.
I'll see if I can edit the cancel buttons to return to the corresponding list page if the user pressed create on the list page not the main page.

**Comment by KavsHub** [comment]
Fixed as of PR #353
